/*
 * FirstUI.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import helpers.CwqHelper;
import helpers.UrlHelper;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Handler;
import java.util.logging.LogRecord;
import javax.crypto.spec.IvParameterSpec;
import javax.swing.ImageIcon;
import org.apache.http.client.utils.HttpClientUtils;
import org.jsoup.Jsoup;
import urls.Constants;
import urls.CwqUrl;
import urls.PaUrl;
import urls.RuanUrl;
import utils.WebUtil;

/**
 *
 * @author  __USER__
 */
public class FirstUI extends javax.swing.JFrame {

	/** Creates new form FirstUI */
	public FirstUI() {
		initComponents();
		initView();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		cb_choose = new javax.swing.JComboBox();
		btn_search = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();
		tv_state = new javax.swing.JLabel();
		jp_code = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jl_image = new javax.swing.JLabel();
		et_code = new javax.swing.JTextField();
		btn_start = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u94fe\u63a5:");

		cb_choose.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "first" }));

		btn_search.setText("\u5f00\u59cb");
		btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_searchMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1)
						.addGap(12, 12, 12)
						.addComponent(cb_choose,
								javax.swing.GroupLayout.PREFERRED_SIZE, 153,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btn_search)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																cb_choose,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																btn_search))));

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jLabel2.setText("\u72b6\u6001:");

		tv_state.setText(" ");

		jLabel3.setText("\u4e8c\u7ef4\u7801:");

		et_code.setColumns(5);

		btn_start.setText("\u5f00\u59cb");
		btn_start.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_startMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jp_codeLayout = new javax.swing.GroupLayout(
				jp_code);
		jp_code.setLayout(jp_codeLayout);
		jp_codeLayout
				.setHorizontalGroup(jp_codeLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jp_codeLayout
										.createSequentialGroup()
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jl_image)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												84, Short.MAX_VALUE)
										.addComponent(
												et_code,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(btn_start)
										.addGap(1, 1, 1)));
		jp_codeLayout
				.setVerticalGroup(jp_codeLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jp_codeLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jp_codeLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jl_image)
														.addComponent(
																et_code,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(btn_start))
										.addContainerGap()));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel2,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(
								jPanel1Layout.createSequentialGroup()
										.addGap(46, 46, 46)
										.addComponent(tv_state)
										.addContainerGap(241, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jp_code,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addContainerGap())
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												267, Short.MAX_VALUE)
										.addContainerGap())
						.addGroup(
								jPanel1Layout.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel2)
										.addContainerGap(252, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jp_code,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												223,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel2)
										.addGap(91, 91, 91)
										.addComponent(tv_state)));

		jMenu1.setText("\u6587\u4ef6");
		jMenuBar1.add(jMenu1);

		jMenu2.setText("\u529f\u80fd");
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 371,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btn_startMouseClicked(java.awt.event.MouseEvent evt) {
		String code = et_code.getText().trim();
		final CwqHelper helper = ((CwqHelper)paurl.getHelper());
		helper.setCode(code);
		helper.getTextArea(jTextArea1);
		new Thread(new Runnable() {
			
			@Override
			public void run() {
				// TODO Auto-generated method stub
				helper.doGetData(paurl);
			}
		}).start();
		
	}

	private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {
		paurl = list.get(cb_choose.getSelectedIndex());
		if (paurl.getType().equals(Constants.TYPE_CWQ)) {
			jp_code.setVisible(true);
			final String url = "http://www.cwq.com/Owner/Account/verify/#" + System.currentTimeMillis();
			final File file = new File("c:\\images\\" + System.currentTimeMillis() +".jpg");
			new Thread(new Runnable() {
				
				@Override
				public void run() {
					// TODO Auto-generated method stub
					try {
//						HttpClientUtil.sendGET("http://www.cwq.com/Owner/Account/login/");
						WebUtil.downImage(url, file.getName(), file.getParent());
						ImageIcon icon = new ImageIcon(file.getPath());
						jl_image.setIcon(icon);
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}).start();
			
		} else if (paurl.getType().equals(Constants.TYPE_RUANWEN)) {
			new Thread(new Runnable() {
				
				@Override
				public void run() {
					// TODO Auto-generated method stub
					paurl.getHelper().getTextArea(jTextArea1);
					paurl.getHelper().doGetData(paurl);
				}
			}).start();
			
		}

	}

	private void initView() {
		jp_code.setVisible(false);
		list = new ArrayList<PaUrl>();
		list.add(new RuanUrl());
		list.add(new CwqUrl());
		int size = list.size();
		String[] chooses = new String[size];
		ArrayList<String> texts = new ArrayList<String>();
		for (PaUrl url : list) {
			texts.add(url.getName());
		}
		chooses = texts.toArray(chooses);
		cb_choose.setModel(new javax.swing.DefaultComboBoxModel(chooses));
	}

	public static void download(String urlString, String filename,
			String savePath) throws Exception {
		// 构造URL  
		URL url = new URL(urlString);
		// 打开连接  
		URLConnection con = url.openConnection();
		//设置请求超时为5s  
		con.setConnectTimeout(5 * 1000);
		// 输入流  
		InputStream is = con.getInputStream();

		// 1K的数据缓冲  
		byte[] bs = new byte[1024];
		// 读取到的数据长度  
		int len;
		// 输出的文件流  
		File sf = new File(savePath);
		if (!sf.exists()) {
			sf.mkdirs();
		}
		OutputStream os = new FileOutputStream(sf.getPath() + "\\" + filename);
		// 开始读取  
		while ((len = is.read(bs)) != -1) {
			os.write(bs, 0, len);
		}
		// 完毕，关闭所有链接  
		os.close();
		is.close();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FirstUI().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btn_search;
	private javax.swing.JButton btn_start;
	private javax.swing.JComboBox cb_choose;
	private javax.swing.JTextField et_code;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JLabel jl_image;
	private javax.swing.JPanel jp_code;
	private javax.swing.JLabel tv_state;
	// End of variables declaration//GEN-END:variables

	private ArrayList<PaUrl> list;
	private PaUrl paurl;
}