/*
 * FirstUI.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import helpers.CwqHelper;
import helpers.UrlHelper;
import helpers.WeiBoHelper;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Handler;
import java.util.logging.LogRecord;
import javax.crypto.spec.IvParameterSpec;
import javax.swing.ImageIcon;
import org.apache.http.client.utils.HttpClientUtils;
import org.json.JSONObject;
import org.jsoup.Jsoup;
import urls.Constants;
import urls.CwqUrl;
import urls.PaUrl;
import urls.RuanUrl;
import urls.WeiBoUrl;
import utils.WebUtil;

/**
 *
 * @author  __USER__
 */
public class FirstUI extends javax.swing.JFrame {

	/** Creates new form FirstUI */
	public FirstUI() {
		initComponents();
		initView();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		cb_choose = new javax.swing.JComboBox();
		btn_search = new javax.swing.JButton();
		jp_code = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jl_image = new javax.swing.JLabel();
		et_code = new javax.swing.JTextField();
		btn_start = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		et_startpage = new javax.swing.JTextField();
		jPanel4 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		tv_state = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tv_result = new javax.swing.JTextArea();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenuBar2 = new javax.swing.JMenuBar();
		jMenuBar3 = new javax.swing.JMenuBar();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u94fe   \u63a5:");

		cb_choose.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "first" }));

		btn_search.setText("\u5f00\u59cb");
		btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_searchMouseClicked(evt);
			}
		});
		btn_search.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_searchActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1).addGap(12, 12, 12)
						.addComponent(cb_choose, 0, 304, Short.MAX_VALUE)
						.addGap(18, 18, 18).addComponent(btn_search)
						.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																btn_search)
														.addComponent(
																cb_choose,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))));

		jLabel3.setText("\u4e8c\u7ef4\u7801:");

		et_code.setColumns(5);

		btn_start.setText("\u5f00\u59cb");
		btn_start.setVerifyInputWhenFocusTarget(false);
		btn_start.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_startMouseClicked(evt);
			}
		});

		jLabel2.setText("\u8d77\u59cb\u9875:");

		et_startpage.setColumns(8);
		et_startpage.setText("1");
		et_startpage.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				et_startpageActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jp_codeLayout = new javax.swing.GroupLayout(
				jp_code);
		jp_code.setLayout(jp_codeLayout);
		jp_codeLayout
				.setHorizontalGroup(jp_codeLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jp_codeLayout
										.createSequentialGroup()
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jl_image,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												60,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												et_code,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												46, Short.MAX_VALUE)
										.addComponent(jLabel2)
										.addGap(18, 18, 18)
										.addComponent(
												et_startpage,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												54,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(39, 39, 39)
										.addComponent(btn_start)
										.addContainerGap()));
		jp_codeLayout
				.setVerticalGroup(jp_codeLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jp_codeLayout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jp_codeLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jl_image,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																25,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addGroup(
																jp_codeLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				et_code,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				et_startpage,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				23,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel2)
																		.addComponent(
																				btn_start)))));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(
						jPanel1Layout
								.createSequentialGroup()
								.addGap(12, 12, 12)
								.addComponent(jp_code,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jp_code,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		jLabel4.setText("\u72b6   \u6001:");

		tv_state.setText("    ");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addComponent(jLabel4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(tv_state)
										.addContainerGap(307, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(tv_state))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		tv_result.setColumns(20);
		tv_result.setRows(5);
		jScrollPane1.setViewportView(tv_result);

		setJMenuBar(jMenuBar3);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(68, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										430, Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										178, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void et_startpageActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btn_startMouseClicked(java.awt.event.MouseEvent evt) {
		String code = et_code.getText().trim();
		String page = et_startpage.getText();
		if(page == null || page.trim().length() == 0) {
			tv_state.setText("请输入请求的起始页");
			return;
		}
		if (paurl.getType().equals(Constants.TYPE_CWQ)) {
			final CwqHelper helper = ((CwqHelper) paurl.getHelper());
			helper.setCode(code);
			helper.getTextArea(tv_result);
			helper.setState(tv_state);
			helper.setStartPage(Integer.valueOf(page));
			new Thread(new Runnable() {

				@Override
				public void run() {
					helper.doGetData(paurl);
				}
			}).start();

		} else if (paurl.getType().equals(Constants.TYPE_WBY)) {
			final WeiBoHelper helper = ((WeiBoHelper) paurl.getHelper());
			helper.setCode(code);
			helper.getTextArea(tv_result);
			helper.setState(tv_state);
			helper.setStartPage(Integer.valueOf(page));
			helper.setKeyTime(key_time);
			new Thread(new Runnable() {

				@Override
				public void run() {
					helper.doGetData(paurl);
				}
			}).start();
		}
	}

	private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {
		tv_result.setText("");
		paurl = list.get(cb_choose.getSelectedIndex());
		if (paurl.getType().equals(Constants.TYPE_CWQ)) {
			jp_code.setVisible(true);
			final String url = "http://www.cwq.com/Owner/Account/verify/#"
					+ System.currentTimeMillis();
			final File file = new File("c:\\images\\"
					+ System.currentTimeMillis() + ".jpg");
			new Thread(new Runnable() {

				@Override
				public void run() {
					try {
						WebUtil.downImage(url, file.getName(), file.getParent());
						ImageIcon icon = new ImageIcon(file.getPath());
						jl_image.setIcon(icon);
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}).start();

		} else if (paurl.getType().equals(Constants.TYPE_RUANWEN)) {
			new Thread(new Runnable() {

				@Override
				public void run() {
					paurl.getHelper().getTextArea(tv_result);
					paurl.getHelper().setState(tv_state);
					paurl.getHelper().doGetData(paurl);
				}
			}).start();

		} else if (paurl.getType().equals(Constants.TYPE_WBY)) {
			jp_code.setVisible(true);
			try {
				key_time = System.currentTimeMillis() + "";
				String url_code = "http://chuanbo.weiboyi.com/hwauth/index/captchaajax?callback=jQuery182034221059567835355_1458271600796&_="
						+ key_time;

				String result = WebUtil.sendGET(url_code);
				int p_start = result.indexOf("{");
				int p_end = result.indexOf("}");
				result = result.substring(p_start, p_end + 1);
				final String url = "http://chuanbo.weiboyi.com"
						+ new JSONObject(result).optString("url");
				final File file = new File("c:\\images\\"
						+ System.currentTimeMillis() + ".jpg");
				new Thread(new Runnable() {

					@Override
					public void run() {
						try {
							WebUtil.downImage(url, file.getName(),
									file.getParent());
							ImageIcon icon = new ImageIcon(file.getPath());
							jl_image.setIcon(icon);
						} catch (Exception e) {
							e.printStackTrace();
						}
					}
				}).start();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}

	}

	private void initView() {
		//设置窗口的属性
		setTitle("蜘蛛侠");
		setSize(600, 400);
		int windowWidth = this.getWidth(); //获得窗口宽
		int windowHeight = this.getHeight(); //获得窗口高
		Toolkit kit = Toolkit.getDefaultToolkit(); //定义工具包
		Dimension screenSize = kit.getScreenSize(); //获取屏幕的尺寸
		int screenWidth = screenSize.width; //获取屏幕的宽
		int screenHeight = screenSize.height; //获取屏幕的高
		this.setLocation(screenWidth / 2 - windowWidth / 2, screenHeight / 2
				- windowHeight / 2);

		/**
		 * 设置显示的数据
		 */
		jp_code.setVisible(false);
		list = new ArrayList<PaUrl>();
		list.add(new RuanUrl());
		list.add(new CwqUrl());
		list.add(new WeiBoUrl());
		int size = list.size();
		String[] chooses = new String[size];
		ArrayList<String> texts = new ArrayList<String>();
		for (PaUrl url : list) {
			texts.add(url.getName());
		}
		chooses = texts.toArray(chooses);
		cb_choose.setModel(new javax.swing.DefaultComboBoxModel(chooses));
	}

	public static void download(String urlString, String filename,
			String savePath) throws Exception {
		// 构造URL  
		URL url = new URL(urlString);
		// 打开连接  
		URLConnection con = url.openConnection();
		//设置请求超时为5s  
		con.setConnectTimeout(5 * 1000);
		// 输入流  
		InputStream is = con.getInputStream();

		// 1K的数据缓冲  
		byte[] bs = new byte[1024];
		// 读取到的数据长度  
		int len;
		// 输出的文件流  
		File sf = new File(savePath);
		if (!sf.exists()) {
			sf.mkdirs();
		}
		OutputStream os = new FileOutputStream(sf.getPath() + "\\" + filename);
		// 开始读取  
		while ((len = is.read(bs)) != -1) {
			os.write(bs, 0, len);
		}
		// 完毕，关闭所有链接  
		os.close();
		is.close();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FirstUI().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btn_search;
	private javax.swing.JButton btn_start;
	private javax.swing.JComboBox cb_choose;
	private javax.swing.JTextField et_code;
	private javax.swing.JTextField et_startpage;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuBar jMenuBar2;
	private javax.swing.JMenuBar jMenuBar3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel jl_image;
	private javax.swing.JPanel jp_code;
	private javax.swing.JTextArea tv_result;
	private javax.swing.JLabel tv_state;
	// End of variables declaration//GEN-END:variables

	private ArrayList<PaUrl> list;
	private PaUrl paurl;
	private String key_time;
}